# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 982e52fe45d5e7071181ad9845cec7be3752ff90ea1d17df6ed5a347009c3dde7de09d61abcbf203b6db5d33807c30ae0a1d97018951090e7569e2d8b953178f

test:
  secret_key_base: 60ebf047e8fb1a6fe89c6f0bdb889be7f0123455af4c575e79dc0d2dfced748fc070e5e81cb7e5f82beb9a667b4fa4ef041d0534889bbcba048f2c80c6e8c13e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
